title: Zhivko Zhelev
description: My Personal Portfolio
author: Zhivko Zhelev
logo: static/img/avatar.png
about: Freelance developer

base.url: https://zhivkoz.github.io
url: /Porfolio
permalink:      /:title/
disqus_shortname: zhivkoz
google_analytics: UA-87160933-1

share:
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
jekyll-mentions:
    base_url: /Portfolio
